version: '3.8'
networks: 
  bridge:
services:
  db:
    image: postgres:14.1-alpine
    container_name: SimbliMasterDB
    hostname: simblimaster
    network_mode: bridge
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SimbliMaster
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/setup.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local